imports:
    - { resource: local/parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: countries.yml }

framework:
    translator:     
        enabled: true
        fallback: en
        logging: %kernel.debug%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    templating:
        engines: ['twig']
        assets_base_urls:
            http:                 []
            ssl:                  []
        assets_version:       ~
        assets_version_format:  %%s?%%s
    default_locale:  en
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    # validation configuration
    validation:
        enabled:              false
        cache:                ~
        enable_annotations:   true
        translation_domain:   validators

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        imagepath: /icup/web/bundles/icuppublicsite/images
        supported_locales: { en: 'GBR', it: 'ITA', fr: 'FRA', de: 'DEU', es: 'ESP', po: 'POL', da: 'DNK' }
        
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ICupPublicSiteBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

parameters:
    db_date_format: Ymd
    db_time_format: Hi
