parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     '3306'
    database_name:     icup
    database_path:     icup

    mailer_transport:  smtp
    mailer_host:       localhost
    
    locale:            da
