security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false          
        ICup\Bundle\PublicSiteBundle\Entity\Doctrine\User:
            algorithm:  bcrypt
            iterations: 13
            encode_as_base64: true          
        
    role_hierarchy:
        ROLE_CLUB_ADMIN:   [ROLE_USER]
        ROLE_EDITOR:       [ROLE_USER]
        ROLE_EDITOR_ADMIN: [ROLE_EDITOR]
        ROLE_ADMIN:        [ROLE_EDITOR_ADMIN, ROLE_CLUB_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [user_db, in_memory]
        in_memory:
            memory:
                users:
                    admin: { password: %security_password%, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: ICup\Bundle\PublicSiteBundle\Entity\Doctrine\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            switch_user: true
            form_login:
                check_path: _security_check
                login_path: _admin_login
            logout:
                path:   _admin_logout
                target: _icup

    access_control:
        - { path: ^/club, roles: ROLE_USER }
        - { path: ^/edit, roles: ROLE_EDITOR }
        - { path: ^/admin, roles: ROLE_EDITOR_ADMIN }

        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1, requires_channel: https }
